[build]
  command = "npm run build" # Lệnh để chạy bước xây dựng
  publish = "dist" # Thư mục chứa các tệp cần triển khai

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"